opt_in_rules:
  - yoda_condition
  - legacy_random
  - operator_usage_whitespace
  - redundant_objc_attribute
  - sorted_imports
  - toggle_bool
  - unused_control_flow_label
  - vertical_whitespace
  - closure_spacing
  - collection_alignment
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - number_separator
  - overridden_super_call
  - override_in_extension
  - prohibited_interface_builder
  - raw_value_for_camel_cased_codable_enum
  - redundant_type_annotation
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - implicitly_unwrapped_optional
  - force_unwrapping
  - force_try
  - force_cast
  - indentation_width
  - empty_string
  - used_import

disabled_rules:
  - trailing_whitespace
  - type_body_length
  - function_body_length
  - file_length

line_length: 99

indentation_width:
  indentation_width: 2
  
identifier_name:
  min_length:
    error: 1

force_unwrapping:
  severity: error

force_cast:
  severity: error

force_try:
  severity: error
